export const globalDisclaimer = '本站为城市地理与居住数据研究工具。挂牌均价、官方成交参考价、招生范围、轨道交通及规划信息均具有时间性，仅供研究参考，不构成入学承诺、购房建议或投资依据，请以主管部门最新公告为准。'

export const dataScopes = [
  {
    id: 'estates',
    label: '小区挂牌均价',
    kind: 'entity',
    status: 'active',
    sourceKey: 'leyoujia_map_avg_listing',
    sourceName: '乐有家深圳小区公开页面',
    sourceUrl: 'https://wap.leyoujia.com/shenzhen/xq/',
    sourceVersion: '动态公开页面',
    termsUrl: null,
    licenseNote: '仅展示经结构化整理的挂牌均价及来源链接，不镜像原始页面。',
    disclaimer: '挂牌均价不是成交价，可能随房源变化而调整。',
  },
  {
    id: 'streets',
    label: '街道行政边界',
    kind: 'overlay',
    status: 'active',
    sourceKey: 'openstreetmap',
    sourceName: 'OpenStreetMap contributors',
    sourceUrl: 'https://www.openstreetmap.org/copyright',
    sourceVersion: 'ODbL',
    termsUrl: 'https://opendatacommons.org/licenses/odbl/',
    licenseNote: '边界经约 5 米简化，仅用于地图展示。',
    disclaimer: '边界可能与主管部门最新行政区划存在时间差。',
  },
  {
    id: 'official-reference-price',
    label: '官方二手住房成交参考价',
    kind: 'entity',
    status: 'active',
    sourceKey: 'official-reference-price-2024',
    sourceName: '深圳市住房和建设局（房地产信息平台）',
    sourceUrl: 'https://zjj.sz.gov.cn/',
    sourceVersion: '2024 年度发布',
    termsUrl: null,
    licenseNote: '官方成交参考价按住宅小区形成，经结构化整理用于地图对比展示，引用来源与年份。',
    disclaimer: '官方成交参考价具有年度性，且与真实成交价存在差异，仅供对比参考。',
  },
  {
    id: 'school-scopes',
    label: '公办学校招生范围（光明·南山）',
    kind: 'overlay',
    status: 'active',
    sourceKey: 'school-scopes-2026',
    sourceName: '光明区、南山区教育局',
    sourceUrl: 'https://www.szgm.gov.cn/132100/135232/xwsq/151714/151730/',
    sourceVersion: '2026 年秋季义务教育学校招生范围（光明 2026-06-11；南山 2026-06-08）',
    termsUrl: null,
    licenseNote: '光明区：学校名称、地址、对应社区和咨询电话整理自官方公告；地图点位由学校地址地理编码生成；学区范围依据官方招生社区名称，按社区中心点 Voronoi 划分近似得到，非官方边界。南山区：学区边界直接采用南山区教育局划片地图的官方多边形（经坐标转换），并附对应小区名单。',
    disclaimer: '招生范围具有年度性，社区对应关系与近似范围不等于保证录取；请以主管部门最新公告为准。',
  },
  {
    id: 'transit',
    label: '轨道交通',
    kind: 'overlay',
    status: 'planned',
    sourceKey: 'mtrsz-lines',
    sourceName: '港铁（深圳）官方线路查询',
    sourceUrl: 'https://www.mtrsz.com.cn/frontend/default/src/channel/line_search.html',
    sourceVersion: '官方动态线路口径',
    termsUrl: null,
    licenseNote: '当前仅用于运营状态核验和原文引用。',
    disclaimer: '规划、建设和运营状态以主管部门及运营方最新公告为准。',
  },
  {
    id: 'planning',
    label: '城市更新与规划',
    kind: 'overlay',
    status: 'planned',
    sourceKey: 'shenzhen-open-data',
    sourceName: '深圳政府数据开放平台',
    sourceUrl: 'https://opendata.sz.gov.cn/',
    sourceVersion: '待授权接入',
    termsUrl: 'https://opendata.sz.gov.cn/maintenance/forward/toTermOfService',
    licenseNote: '需通过平台认证和订阅接口，不转让或镜像原始数据。',
    disclaimer: '列入计划、公示或意愿征集不代表必然实施。',
  },
]
